version: '3.4'

services:
  postgres:
    container_name: postgres_container
    image: postgres:alpine
    environment:
      POSTGRES_DB: "autorizador_core"
      POSTGRES_USER: "core_user"
      POSTGRES_PASSWORD: "core_user"
    volumes:
      - "/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  rabbitMQ:
    image: rabbitmq:3-management
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "autorizador"
      RABBITMQ_DEFAULT_PASS: "autorizador_pass"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    container_name: rabbitmq-autorizador
    volumes:
      - "./enabled_plugins:/data/rabbitmq/enabled_plugins"

