spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

springdoc:
  swagger-ui:
    path: /docs.html

server:
  servlet:
    context-path: /dev